import './globals.css'
import {Poppins, Exo_2} from 'next/font/google'
import NavBar from "@/components/NavBar/NavBar";
import ProgressProvider from "@/provider/ProgressProvider";
import Footer from "@/components/Footer/Footer";

const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins"
})


const exo = Exo_2({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["cyrillic", "cyrillic-ext", "latin", "latin-ext", "vietnamese"],
    variable: "--font-exo-pro"
})




export  const metadata = {
    title: "Design Agency",
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (<html lang="en">
        <body className={`${poppins.variable} ${exo.variable}`}>
        <NavBar/>
        <ProgressProvider/>
        {children}
        <Footer/>
        </body>
        </html>)
}
